version: '3'
services:
  logstash:
    image: logstash:7.0.1
    container_name: logstash
    command: bin/logstash -e 'input { beats { port => "5044" } } output { stdout {} }'
    ports:
    - "5044:5044"
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.0.1
    container_name: filebeat
    links:
    - logstash
